// generated by stringer -type Enum .; DO NOT EDIT

package enum

import "fmt"

const _Enum_name = "Flag1Flag2Flag3"

var _Enum_index = [...]uint8{0, 5, 10, 15}

func (i Enum) String() string {
	i -= 1
	if i < 0 || i >= Enum(len(_Enum_index)-1) {
		return fmt.Sprintf("Enum(%d)", i+1)
	}
	return _Enum_name[_Enum_index[i]:_Enum_index[i+1]]
}
